name: Angular CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.14.0]

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js v22.14.0 (LTS)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Compile Application
      run: npm run build
